"""user_session column for auth user

Revision ID: 279bef8b413b
Revises: f50b8cec54bc
Create Date: 2022-11-07 12:30:24.374696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279bef8b413b'
down_revision = 'f50b8cec54bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_session', sa.String(length=24), nullable=True), schema='auth')
    op.create_index(op.f('ix_auth_users_last_session'), 'users', ['last_session'], unique=True, schema='auth')
    op.alter_column('brownfields', 'altitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=False,
               schema='brownfields')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brownfields', 'altitude',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=False,
               schema='brownfields')
    op.drop_index(op.f('ix_auth_users_last_session'), table_name='users', schema='auth')
    op.drop_column('users', 'last_session', schema='auth')
    # ### end Alembic commands ###
