"""init for brownfields

Revision ID: 2d0441673eb5
Revises: 
Create Date: 2022-10-30 13:00:36.678499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d0441673eb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area_sizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_index(op.f('ix_area_sizes_id'), 'area_sizes', ['id'], unique=False)
    op.create_table('degradation_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_index(op.f('ix_degradation_levels_id'), 'degradation_levels', ['id'], unique=False)
    op.create_table('economic_potentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_index(op.f('ix_economic_potentials_id'), 'economic_potentials', ['id'], unique=False)
    op.create_table('environmental_burden_inclusions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_index(op.f('ix_environmental_burden_inclusions_id'), 'environmental_burden_inclusions', ['id'], unique=False)
    op.create_table('infrastructure_availabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_index(op.f('ix_infrastructure_availabilities_id'), 'infrastructure_availabilities', ['id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_table('natural_and_architectural_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_index(op.f('ix_natural_and_architectural_values_id'), 'natural_and_architectural_values', ['id'], unique=False)
    op.create_table('original_functional_utilizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_index(op.f('ix_original_functional_utilizations_id'), 'original_functional_utilizations', ['id'], unique=False)
    op.create_table('ownership_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_index(op.f('ix_ownership_types_id'), 'ownership_types', ['id'], unique=False)
    op.create_table('residentional_area_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_index(op.f('ix_residentional_area_categories_id'), 'residentional_area_categories', ['id'], unique=False)
    op.create_table('revitalizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_index(op.f('ix_revitalizations_id'), 'revitalizations', ['id'], unique=False)
    op.create_table('settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_index(op.f('ix_settlements_id'), 'settlements', ['id'], unique=False)
    op.create_table('utilizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_index(op.f('ix_utilizations_id'), 'utilizations', ['id'], unique=False)
    op.create_table('brownfields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=256), nullable=False),
    sa.Column('area_ha', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('mapping_year', sa.Integer(), nullable=False),
    sa.Column('altitude', sa.Float(precision=4), nullable=False),
    sa.Column('ownership_type_id', sa.Integer(), nullable=True),
    sa.Column('original_functional_utilization_id', sa.Integer(), nullable=True),
    sa.Column('utilization_id', sa.Integer(), nullable=True),
    sa.Column('area_size_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('degradation_level_id', sa.Integer(), nullable=True),
    sa.Column('residentional_area_category_id', sa.Integer(), nullable=True),
    sa.Column('settlement_id', sa.Integer(), nullable=True),
    sa.Column('infrastructure_availability_id', sa.Integer(), nullable=True),
    sa.Column('natural_and_architectural_value_id', sa.Integer(), nullable=True),
    sa.Column('revitalization_id', sa.Integer(), nullable=True),
    sa.Column('economic_potential_id', sa.Integer(), nullable=True),
    sa.Column('environmental_burden_inclusion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['area_size_id'], ['area_sizes.id'], ),
    sa.ForeignKeyConstraint(['degradation_level_id'], ['degradation_levels.id'], ),
    sa.ForeignKeyConstraint(['economic_potential_id'], ['economic_potentials.id'], ),
    sa.ForeignKeyConstraint(['environmental_burden_inclusion_id'], ['environmental_burden_inclusions.id'], ),
    sa.ForeignKeyConstraint(['infrastructure_availability_id'], ['infrastructure_availabilities.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['natural_and_architectural_value_id'], ['natural_and_architectural_values.id'], ),
    sa.ForeignKeyConstraint(['original_functional_utilization_id'], ['original_functional_utilizations.id'], ),
    sa.ForeignKeyConstraint(['ownership_type_id'], ['ownership_types.id'], ),
    sa.ForeignKeyConstraint(['residentional_area_category_id'], ['residentional_area_categories.id'], ),
    sa.ForeignKeyConstraint(['revitalization_id'], ['revitalizations.id'], ),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], ),
    sa.ForeignKeyConstraint(['utilization_id'], ['utilizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brownfields_id'), 'brownfields', ['id'], unique=False)
    op.drop_table('Kokoland')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Kokoland',
    sa.Column('13', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.drop_index(op.f('ix_brownfields_id'), table_name='brownfields')
    op.drop_table('brownfields')
    op.drop_index(op.f('ix_utilizations_id'), table_name='utilizations')
    op.drop_table('utilizations')
    op.drop_index(op.f('ix_settlements_id'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_revitalizations_id'), table_name='revitalizations')
    op.drop_table('revitalizations')
    op.drop_index(op.f('ix_residentional_area_categories_id'), table_name='residentional_area_categories')
    op.drop_table('residentional_area_categories')
    op.drop_index(op.f('ix_ownership_types_id'), table_name='ownership_types')
    op.drop_table('ownership_types')
    op.drop_index(op.f('ix_original_functional_utilizations_id'), table_name='original_functional_utilizations')
    op.drop_table('original_functional_utilizations')
    op.drop_index(op.f('ix_natural_and_architectural_values_id'), table_name='natural_and_architectural_values')
    op.drop_table('natural_and_architectural_values')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_infrastructure_availabilities_id'), table_name='infrastructure_availabilities')
    op.drop_table('infrastructure_availabilities')
    op.drop_index(op.f('ix_environmental_burden_inclusions_id'), table_name='environmental_burden_inclusions')
    op.drop_table('environmental_burden_inclusions')
    op.drop_index(op.f('ix_economic_potentials_id'), table_name='economic_potentials')
    op.drop_table('economic_potentials')
    op.drop_index(op.f('ix_degradation_levels_id'), table_name='degradation_levels')
    op.drop_table('degradation_levels')
    op.drop_index(op.f('ix_area_sizes_id'), table_name='area_sizes')
    op.drop_table('area_sizes')
    # ### end Alembic commands ###
