"""empty message

Revision ID: 46900a9543c7
Revises: 1e195ae311ba
Create Date: 2022-11-15 22:26:01.464978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46900a9543c7'
down_revision = '1e195ae311ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brownfields', 'altitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=False,
               schema='brownfields')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brownfields', 'altitude',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=False,
               schema='brownfields')
    # ### end Alembic commands ###
