"""size update for last_session in user

Revision ID: 4a18314e6c39
Revises: 279bef8b413b
Create Date: 2022-11-07 12:36:51.442779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a18314e6c39'
down_revision = '279bef8b413b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_session',
               existing_type=sa.VARCHAR(length=24),
               type_=sa.String(length=64),
               existing_nullable=True,
               schema='auth')
    op.alter_column('brownfields', 'altitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=False,
               schema='brownfields')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brownfields', 'altitude',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=False,
               schema='brownfields')
    op.alter_column('users', 'last_session',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=24),
               existing_nullable=True,
               schema='auth')
    # ### end Alembic commands ###
