"""changes is_active false to True + is_admin

Revision ID: 4e3b2c742f26
Revises: 91a77fee2abb
Create Date: 2022-12-07 15:11:59.791155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e3b2c742f26'
down_revision = '91a77fee2abb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False), schema='auth')
    op.alter_column('brownfields', 'altitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=False,
               schema='brownfields')
    op.create_index(op.f('ix_brownfields_colors_id'), 'colors', ['id'], unique=False, schema='brownfields')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brownfields_colors_id'), table_name='colors', schema='brownfields')
    op.alter_column('brownfields', 'altitude',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=False,
               schema='brownfields')
    op.drop_column('users', 'is_admin', schema='auth')
    # ### end Alembic commands ###
