"""empty message

Revision ID: be912bf51b2b
Revises: 9e9eba2d20e4
Create Date: 2023-01-09 20:23:00.755580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be912bf51b2b'
down_revision = '9e9eba2d20e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
