"""Color_id for brownfields back to nullable = Flase

Revision ID: c48d99f561c9
Revises: 87b770a6cc9f
Create Date: 2022-11-28 17:37:08.047429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c48d99f561c9'
down_revision = '87b770a6cc9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brownfields', 'altitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=False,
               schema='brownfields')
    op.alter_column('brownfields', 'color_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='brownfields')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brownfields', 'color_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='brownfields')
    op.alter_column('brownfields', 'altitude',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=False,
               schema='brownfields')
    # ### end Alembic commands ###
