"""added polygon column to brownfield

Revision ID: eaff23a79349
Revises: 2475466e676c
Create Date: 2023-01-10 13:27:00.216394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaff23a79349'
down_revision = '2475466e676c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brownfields', 'altitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=False,
               schema='brownfields')
    op.create_index('idx_brownfields_polygon', 'brownfields', ['polygon'], unique=False, schema='brownfields', postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_brownfields_polygon', table_name='brownfields', schema='brownfields', postgresql_using='gist')
    op.alter_column('brownfields', 'altitude',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=False,
               schema='brownfields')
    # ### end Alembic commands ###
