"""brownfield uuid constraint added nullable=False

Revision ID: ef56e037d58d
Revises: f76182f08882
Create Date: 2022-11-03 23:44:32.733000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef56e037d58d'
down_revision = 'f76182f08882'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brownfields', 'image_directory_uuid',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               schema='brownfields')
    op.alter_column('brownfields', 'altitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=False,
               schema='brownfields')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brownfields', 'altitude',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=False,
               schema='brownfields')
    op.alter_column('brownfields', 'image_directory_uuid',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               schema='brownfields')
    # ### end Alembic commands ###
