"""unqiue constraint to email for user

Revision ID: f50b8cec54bc
Revises: 36f2f1cb5e5f
Create Date: 2022-11-06 09:16:03.927985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f50b8cec54bc'
down_revision = '36f2f1cb5e5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auth_users_email', table_name='users', schema='auth')
    op.create_index(op.f('ix_auth_users_email'), 'users', ['email'], unique=True, schema='auth')
    op.alter_column('brownfields', 'altitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=False,
               schema='brownfields')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brownfields', 'altitude',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=False,
               schema='brownfields')
    op.drop_index(op.f('ix_auth_users_email'), table_name='users', schema='auth')
    op.create_index('ix_auth_users_email', 'users', ['email'], unique=False, schema='auth')
    # ### end Alembic commands ###
