"""added uuid to brownfield

Revision ID: f76182f08882
Revises: f23f8a9335c1
Create Date: 2022-11-03 23:43:03.075020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f76182f08882'
down_revision = 'f23f8a9335c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brownfields', sa.Column('image_directory_uuid', sa.String(length=128), nullable=True), schema='brownfields')
    op.alter_column('brownfields', 'altitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=False,
               schema='brownfields')
    op.alter_column('brownfields', 'ownership_type_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='brownfields')
    op.alter_column('brownfields', 'original_functional_utilization_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='brownfields')
    op.alter_column('brownfields', 'utilization_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='brownfields')
    op.alter_column('brownfields', 'area_size_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='brownfields')
    op.alter_column('brownfields', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='brownfields')
    op.alter_column('brownfields', 'degradation_level_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='brownfields')
    op.alter_column('brownfields', 'residentional_area_category_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='brownfields')
    op.alter_column('brownfields', 'settlement_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='brownfields')
    op.alter_column('brownfields', 'infrastructure_availability_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='brownfields')
    op.alter_column('brownfields', 'natural_and_architectural_value_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='brownfields')
    op.alter_column('brownfields', 'revitalization_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='brownfields')
    op.create_index(op.f('ix_brownfields_brownfields_image_directory_uuid'), 'brownfields', ['image_directory_uuid'], unique=False, schema='brownfields')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brownfields_brownfields_image_directory_uuid'), table_name='brownfields', schema='brownfields')
    op.alter_column('brownfields', 'revitalization_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='brownfields')
    op.alter_column('brownfields', 'natural_and_architectural_value_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='brownfields')
    op.alter_column('brownfields', 'infrastructure_availability_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='brownfields')
    op.alter_column('brownfields', 'settlement_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='brownfields')
    op.alter_column('brownfields', 'residentional_area_category_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='brownfields')
    op.alter_column('brownfields', 'degradation_level_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='brownfields')
    op.alter_column('brownfields', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='brownfields')
    op.alter_column('brownfields', 'area_size_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='brownfields')
    op.alter_column('brownfields', 'utilization_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='brownfields')
    op.alter_column('brownfields', 'original_functional_utilization_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='brownfields')
    op.alter_column('brownfields', 'ownership_type_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='brownfields')
    op.alter_column('brownfields', 'altitude',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=False,
               schema='brownfields')
    op.drop_column('brownfields', 'image_directory_uuid', schema='brownfields')
    # ### end Alembic commands ###
