"""Colors table for brownfields (default = 1)

Revision ID: f83e780635a9
Revises: fc7fd665cfe8
Create Date: 2022-11-28 17:30:03.072489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83e780635a9'
down_revision = 'fc7fd665cfe8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brownfields', sa.Column('color_id', sa.Integer(), nullable=False), schema='brownfields')
    op.alter_column('brownfields', 'altitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=False,
               schema='brownfields')
    op.create_foreign_key(None, 'brownfields', 'colors', ['color_id'], ['id'], source_schema='brownfields', referent_schema='brownfields')
    op.create_index(op.f('ix_brownfields_colors_id'), 'colors', ['id'], unique=False, schema='brownfields')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brownfields_colors_id'), table_name='colors', schema='brownfields')
    op.drop_constraint(None, 'brownfields', schema='brownfields', type_='foreignkey')
    op.alter_column('brownfields', 'altitude',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=False,
               schema='brownfields')
    op.drop_column('brownfields', 'color_id', schema='brownfields')
    # ### end Alembic commands ###
