"""Colors table for brownfields

Revision ID: fc7fd665cfe8
Revises: 6f0222c03d77
Create Date: 2022-11-28 17:22:30.220086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc7fd665cfe8'
down_revision = '6f0222c03d77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('hex_value', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='brownfields'
    )
    op.create_index(op.f('ix_brownfields_colors_id'), 'colors', ['id'], unique=False, schema='brownfields')
    op.add_column('brownfields', sa.Column('color_id', sa.Integer(), nullable=False), schema='brownfields')
    op.alter_column('brownfields', 'altitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=False,
               schema='brownfields')
    op.create_foreign_key(None, 'brownfields', 'colors', ['color_id'], ['id'], source_schema='brownfields', referent_schema='brownfields')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'brownfields', schema='brownfields', type_='foreignkey')
    op.alter_column('brownfields', 'altitude',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=False,
               schema='brownfields')
    op.drop_column('brownfields', 'color_id', schema='brownfields')
    op.drop_index(op.f('ix_brownfields_colors_id'), table_name='colors', schema='brownfields')
    op.drop_table('colors', schema='brownfields')
    # ### end Alembic commands ###
