version: '3'
services:
  backend_app:
    image: tetropolix/brownfields_app:1.0
    restart: always
    depends_on:
      - db
    volumes:
      - $HOST_VOLUME=$BROWNFIELD_IMAGES_DIR
    environment:
      - SQLALCHEMY_DATABASE_URL=$SQLALCHEMY_DATABASE_URL
      - SECRET_KEY=$SECRET_KEY
      - BROWNFIELD_IMAGES_DIR=$BROWNFIELD_IMAGES_DIR
    ports:
      - target: 8000
        published: 50002